name: test-deploy
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: hello_world
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
        env:
          DB_HOST: localhost
      - run: pytest helloworld/tests.py
